---

# module versions
versions:
  rejson: 2.0.9
  redistimeseries: 1.6.17
  redisearch: 2.4.11
  redisgraph: 2.8.16
  redisbloom: 2.2.17
  nodejs: v14.19.0
  redis: 7.0.4
  redis-stack: 99.99.99
  redis-stack-server: 99.99.99
  redisinsight: 2.4.0
  redisinsight-web: 2.4.0

# common package variables
email: Redis OSS <oss@redislabs.com>
license: Redis Source Available License
vendor: Redis Inc
url: "https://redis.io"

redis-stack:
  product: redis-stack
  summary: redis-stack installs a Redis server with additional database capabilities and the visualisation tool RedisInsight.
  description: |
    Redis Stack Server includes the Redis server with the following additional capabilities installed and ready to use:

    RedisJSON: Store, retrieve and perform atomic updates on JSON documents
    RedisSearch: Full text search and secondary indexing over hashes and JSON documents
    RedisTimeSeries: Store and manage time series data in Redis, perform aggregated queries and downsampling
    RedisBloom: Extends Redis to include popular probabilistic data structures including Bloom and Cuckoo filters, Count-Min Sketch and Top-K
    RedisGraph: Adds graph database and Cypher query capabilities to Redis

    Manage your Redis server and view your data with the RedisInsight graphical tool, which is also included in this package.

redis-stack-server:
  product: redis-stack-server
  summary: Redis Stack Server installs a Redis server with additional database capabilities.
  description: |
    Redis Stack Server includes the Redis server with the following additional capabilities installed and ready to use:

    RedisJSON: Store, retrieve and perform atomic updates on JSON documents
    RedisSearch: Full text search and secondary indexing over hashes and JSON documents
    RedisTimeSeries: Store and manage time series data in Redis, perform aggregated queries and downsampling
    RedisBloom: Extends Redis to include popular probabilistic data structures including Bloom and Cuckoo filters, Count-Min Sketch and Top-K
    RedisGraph: Adds graph database and Cypher query capabilities to Redis

# note the version - no underscores or hyphens allowed
redisinsight-web:
  product: redisinsight-web
  summary: A graphical tool for visualizing data and managing Redis databases
  description: RedisInsight is an easy to use graphical tool that enables you to visualize and manage data in Redis databases.  Connect to multiple Redis servers, browse and edit data, and view operating metrics.  Use RedisInsight with open source Redis, Redis Cloud, Redis Enterprise and Amazon ElastiCache.  RedisInsight has specialized views for many Redis data types, and supports popular modules including RediSearch and RedisJSON.

redisinsight:
  product: redisinsight
  summary: A graphical tool for visualizing data and managing Redis databases
  description: RedisInsight is an easy to use graphical tool that enables you to visualize and manage data in Redis databases.  Connect to multiple Redis servers, browse and edit data, and view operating metrics.  Use RedisInsight with open source Redis, Redis Cloud, Redis Enterprise and Amazon ElastiCache.  RedisInsight has specialized views for many Redis data types, and supports popular modules including RediSearch and RedisJSON.

# uid/gid
product_user: nobody
product_group: nobody
