---

# module versions
rejson: 2.0.7
redistimeseries: 1.6.7
redisearch: 2.4.0
redisgraph: 2.8.8
redisbloom: 2.2.12
redisinsight: 2.0.4-preview
nodejs: v14.19.0

# common package variables
email: Redis OSS <oss@redislabs.com>
license: MIT
vendor: Redis Inc
url: "https://redis.io"

redis-stack:
  version: 0.0.1
  product: redis-stack
  summary: redis-stack installs a Redis server with additional database capabilities and the visualisation toll RedisInsight.
  description: |
    Redis Stack Server includes the Redis server with the following additional capabilities installed and ready to use:

    RedisJSON: Store, retrieve and perform atomic updates on JSON documents
    RedisSearch: Full text search and secondary indexing over hashes and JSON documents
    RedisTimeSeries: Store and manage time series data in Redis, perform aggregated queries and downsampling
    RedisBloom: Extends Redis to include popular probabilistic data structures including Bloom and Cuckoo filters, Count-Min Sketch and Top-K
    RedisGraph: Adds graph database and Cypher query capabilities to Redis
    
    Manage your Redis server and view your data with the RedisInsight graphical tool, which is also included in this package.

redis-stack-server:
  version: 0.0.1
  product: redis-stack-server
  summary: redis-stack installs a Redis server with additional database capabilities.
  description: |
    Redis Stack Server includes the Redis server with the following additional capabilities installed and ready to use:

    RedisJSON: Store, retrieve and perform atomic updates on JSON documents
    RedisSearch: Full text search and secondary indexing over hashes and JSON documents
    RedisTimeSeries: Store and manage time series data in Redis, perform aggregated queries and downsampling
    RedisBloom: Extends Redis to include popular probabilistic data structures including Bloom and Cuckoo filters, Count-Min Sketch and Top-K
    RedisGraph: Adds graph database and Cypher query capabilities to Redis

# note the version - no underscores or hyphens allowed
redisinsight-web:
  version: 2.0.4preview
  product: redisinsight-web
  summary: RI Web summary
  description: RI Web placeholder

# uid/gid
product_user: nobody
product_group: nobody